# yaml 配置实例
version: '3'
services:
  canyon:
    image: zhangtao25/canyon:dev
    restart: always
    container_name: canyon-project
    ports:
      - 26000:8080
    networks:
      - canyon-network
    volumes:
      - ./conf/application.yml:/usr/src/app/packages/canyon-api/conf/application.yml
networks:
  canyon-network:
    # Use a custom driver
    driver: self-hosted_canyon-network
