datasource:
  mysql:
    type: mysql
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    database: canyon
    userEntityTableName: user
    repoEntityTableName: repo
    coverageEntityTableName: coverage
  mongodb:
    type: mongodb
    host: 127.0.0.1
    port: 27017
    username: root
    password: root
    database: canyon

gitlab:
  application:
    clientId: clientId
    clientSecret: clientSecret
    redirectUri: redirectUri
    uri: uri
